SE1611_Group4_A3/SE1611_Group4_A3/Models/Cart.cs
namespace SE1607_Group4_A3.Models
{
    public partial class Cart
    {
        public int RecordId { get; set; }
        public string CartId { get; set; } = null!;
        public int AlbumId { get; set; }
        public int Count { get; set; }
        public DateTime DateCreated { get; set; }

        public virtual Album Album { get; set; } = null!;
    }
}

SE1611_Group4_A3/SE1611_Group4_A3/Pages/Cart.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using SE1607_Group4_A3.Models;

namespace SE1607_Group4_A3.Pages
{
    public class CartModel : PageModel
    {
        private readonly MusicStoreContext _context;
        public List<Cart> Carts { get; set; }
        public decimal GrandTotal { get; set; }
        public CartModel(MusicStoreContext context)
        {
            _context = context;
            Carts = new List<Cart>();
            GrandTotal = 0;

        }
        public IActionResult OnGet()
        {
            string username = HttpContext.Session.GetString(Constant.userSessionKey) ?? string.Empty;
            if (string.IsNullOrEmpty(username)) { return RedirectToPage("Login"); }
            Carts = _context.Carts.Include(c => c.Album).Where(c => c.CartId.Equals(username)).ToList();
            GrandTotal = Carts.Sum(c => c.Album.Price * c.Count);
            return Page();
        }
        public void OnGetRemove(int id)
        {
            var cart = _context.Carts.Find(id);
            if (cart != null)
            {
                if (cart.Count > 1)
                {
                    cart.Count -= 1;
                    _context.Carts.Update(cart);
                }
                else
                {
                    _context.Carts.Remove(cart);
                }
            }
            _context.SaveChanges();
            OnGet();
        }
        public void OnGetClickTitle(int id)
        {
            var cart = _context.Carts.Find(id);
            if (cart != null)
            {
                cart.Count += 1;
                _context.Carts.Update(cart);
            }
            _context.SaveChanges();
            OnGet();
        }
    }
}

SE1611_Group4_A3/SE1611_Group4_A3/Pages/Checkout.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using SE1607_Group4_A3.Models;

namespace SE1607_Group4_A3.Pages
{
    public class CheckoutModel : PageModel
    {
        private readonly MusicStoreContext _context;
        [BindProperty]
        public Order Order { get; set; }
        public decimal Total { get; set; }
        public User user { get; set; }
        public CheckoutModel(MusicStoreContext context)
        {
            _context = context;
            Total = 0;
        }
        public IActionResult OnGet()
        {
            string username = HttpContext.Session.GetString(Constant.userSessionKey);
            if (string.IsNullOrEmpty(username)) { return RedirectToPage("Login"); }
            user = _context.Users.FirstOrDefault(u => u.UserName == username);
            if (user is null) { return RedirectToPage("Login"); }


            Total = _context.Carts.Where(c => c.CartId.Equals(username)).Include(c => c.Album).Sum(c => c.Album.Price * c.Count);
            return Page();
        }
        public IActionResult OnPostOrder()
        {
            string username = HttpContext.Session.GetString(Constant.userSessionKey);
            if (string.IsNullOrEmpty(username)) { return RedirectToPage("Login"); }
            Order.OrderDetails = _context.Carts.Where(c => c.CartId.Equals(username)).Include(c => c.Album).Select(c => new OrderDetail
            {
                AlbumId = c.AlbumId,
                Quantity = c.Count,
                UnitPrice = c.Album.Price,
            }).ToList();
            Order.OrderDate = DateTime.Now;
            _context.Orders.Add(Order);
            _context.Carts.RemoveRange(_context.Carts);
            _context.SaveChanges();
            return RedirectToPage("Shopping");
        }
    }
}

SE1611_Group4_A3/SE1611_Group4_A3/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace SE1607_Group4_A3.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

SE1611_Group4_A3/SE1611_Group4_A3/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace SE1607_Group4_A3.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;

        public IndexModel(ILogger<IndexModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {

        }
    }
}

SE1611_Group4_A3/SE1611_Group4_A3/Pages/Login.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using SE1607_Group4_A3.Models;
using SE1607_Group4_A3.Models.DTO;
using System.Text;

namespace SE1607_Group4_A3.Pages
{
    public class LoginModel : PageModel
    {
        private readonly MusicStoreContext _context;
        [BindProperty]
        public UserDTO User { get; set; }
        public LoginModel(MusicStoreContext musicStoreContext)
        {
            _context = musicStoreContext;
        }

        public void OnGet()
        {
        }
        public IActionResult OnPost()
        {
            if (!ModelState.IsValid) { return Page(); }
            if (User == null) { return Page(); }
            User u = null;
            if (!_context.Users.Any(u => u.UserName.Equals(User.UserName) && u.Password.Equals(User.Password)))
            {
                ModelState.AddModelError("LoginFailed", "Invalid username or password");
                return Page();
            }
            u = _context.Users.FirstOrDefault(u => u.UserName.Equals(User.UserName) && u.Password.Equals(User.Password));
            HttpContext.Session.Set(Constant.userSessionRoleKey, Encoding.UTF8.GetBytes(u.Role.ToString()));
            HttpContext.Session.Set(Constant.userSessionKey, Encoding.UTF8.GetBytes(User.UserName.ToString()));
            return RedirectToPage("Index");
        }
        public void OnGetLogout()
        {
            if (HttpContext.Session.Keys.Contains(Constant.userSessionKey))
            {
                HttpContext.Session.Remove(Constant.userSessionKey);
            }
        }
    }
}

SE1611_Group4_A3/SE1611_Group4_A3/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace SE1607_Group4_A3.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

SE1611_Group4_A3/SE1611_Group4_A3/Pages/Shopping.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SE1607_Group4_A3.Models;

namespace SE1607_Group4_A3.Pages
{
    public class ShoppingModel : PageModel
    {
        private readonly MusicStoreContext _context;
        public List<SelectListItem> Genres { get; set; }
        public List<Album> Albums { get; set; }
        private const int PAGE_TAKE = 3;
        public int TotalPage { get; set; }
        public int Count { get; set; }
        [BindProperty(SupportsGet = true)]
        public new int PageNum { get; set; }
        [BindProperty(SupportsGet = true)]
        public string? Title { get; set; }
        [BindProperty(SupportsGet = true)]
        public int? GenreId { get; set; }
        [BindProperty]
        public int AlbumId { get; set; }
        public ShoppingModel(MusicStoreContext musicStoreContext)
        {
            _context = musicStoreContext;
            Genres = new List<SelectListItem>();

            Genres = _context.Genres.Select(genre => new SelectListItem
            {
                Value = genre.GenreId.ToString(),
                Text = genre.Name,
            }).ToList();
            Genres.Add(new SelectListItem
            {
                Value = string.Empty,
                Text = "-------All------",
                Selected = true

            });
            Albums = _context.Albums.Include(a => a.Artist).Include(a => a.Genre).Skip(0).Take(3).ToList();
            Count = _context.Albums.Count();
            PageNum = 0;
            TotalPage = Count / PAGE_TAKE;
        }
        public IActionResult OnGet()
        {
            IQueryable<Album> albums = _context.Albums.AsQueryable();
            if (GenreId != null)
            {
                albums = albums.Where(a => a.GenreId == GenreId);
            }
            if (!string.IsNullOrEmpty(Title))
            {
                albums = albums.Where(a => a.Title.Equals(Title));
            }
            Count = albums.Count();
            TotalPage = Count / PAGE_TAKE;
            int skip = PageNum * PAGE_TAKE;
            if (skip > Count)
            {
                skip = TotalPage * PAGE_TAKE;
                PageNum = TotalPage;
            }
            Albums = albums.Include(a => a.Artist).Include(a => a.Genre).Skip(skip).Take(PAGE_TAKE).ToList();
            return Page();
        }
        public IActionResult OnPostAddCart()
        {
            string username = HttpContext.Session.GetString(Constant.userSessionKey) ?? string.Empty;
            if (string.IsNullOrEmpty(username)) { return RedirectToPage("Login"); }
            var user = _context.Users.FirstOrDefault(u => u.UserName == username);
            if (user == null) { return RedirectToPage("Login"); }
            var cart = _context.Carts.FirstOrDefault(c => c.AlbumId == AlbumId && c.CartId == username);
            if (cart != null)
            {
                cart.Count += 1;
                _context.Entry(cart).State = EntityState.Modified;
            }
            else
            {
                 cart = new()
                {
                    AlbumId = AlbumId,
                    DateCreated = DateTime.Now,
                    Count = 1,
                    CartId = user.UserName,
                };
                _context.Carts.Add(cart);
              
            }
            _context.SaveChanges();
            return RedirectToPage("Cart");
        }
    }
}

SE1611_Group4_A3/SE1611_Group4_A3/Pages/Cart.cshtml
@page
@model SE1607_Group4_A3.Pages.CartModel
@{
}
<style>
    #cartTable{
        border: 2px solid var(--bs-primary)
    }
    #tfoot{
        border-top: 2px dotted black
    }
</style>
@{
    string username = HttpContext.Session.GetString(Constant.userSessionKey);
    bool checkoutBtnDisabled = Model.GrandTotal <= 0 || string.IsNullOrEmpty(username);
}
<h1>Cart</h1>
@if (checkoutBtnDisabled)
{
    <a class="btn btn-primary disabled"  href="#">Checkout</a>
} else
{
   <a class="btn btn-primary"  asp-page="/Checkout">Checkout</a> 
}

<table class="table mt-3" id="cartTable">
    <thead>
        <tr>
            <th>Album</th>
            <th>Price</th>
            <th>Count</th>
            <th>Date created</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @{
            if (Model.Carts != null  && Model.Carts.Count > 0)
            {
                 foreach(var cart in Model.Carts)
                {
                    @:<tr>
                        <td>
                            <a asp-page-handler="ClickTitle" asp-route-id="@cart.RecordId"> @cart.Album.Title                            </a>
                        </td>
                        <td>@cart.Album.Price</td>
                        <td>@cart.Count</td>
                        <td>@(cart.DateCreated.ToString("dd/MM/yyyy"))</td>
                        <td>
                            <a asp-page-handler="remove" asp-route-id="@cart.RecordId">Remove from cart</a>
                        </td>
                    @:</tr>
            
                }
            }
        }
        <tr id="tfoot">
            <th></th>
            <th></th>
            <th>Total: @Model.GrandTotal</th>
            <th></th>
            <th></th>
        </tr>
    </tbody>
</table>

SE1611_Group4_A3/SE1611_Group4_A3/Pages/Checkout.cshtml
@page
@model SE1607_Group4_A3.Pages.CheckoutModel
@{
}
<h1>Checkout View</h1>
<h2>Order</h2>
<hr />
<div class="row mt-2">
    <div class="col-md-6">
    <form asp-action="POST">
        <label asp-for="Order.FirstName"></label><br />
        <input class="form-control" asp-for="Order.FirstName" value="@Model.user.FirstName" /><br />
        <label asp-for="Order.LastName"></label><br />
        <input class="form-control" asp-for="Order.LastName" value="@Model.user.LastName" /><br />
        <label asp-for="Order.Address"></label><br />
        <input class="form-control" asp-for="Order.Address" value="@Model.user.Address" /><br />
        <label asp-for="Order.City"></label><br />
        <input class="form-control" asp-for="Order.City" value="@Model.user.City" /><br />
        <label asp-for="Order.State"></label><br />
        <input class="form-control" asp-for="Order.State" value="@Model.user.State" /><br />
        <label asp-for="Order.Country"></label><br />
        <input class="form-control" asp-for="Order.Country" value="@Model.user.Country" /><br />
        <label asp-for="Order.Phone"></label><br />
        <input class="form-control" asp-for="Order.Phone" value="@Model.user.Phone" /><br />
        <label asp-for="Order.Email"></label><br />
        <input class="form-control" asp-for="Order.Email" value="@Model.user.Email" /><br />
        <label asp-for="Order.Total"></label><br />
        <input class="form-control" asp-for="Order.Total" readonly value="@Model.Total" /><br />
        <button class="btn btn-primary" asp-page-handler="order">Order</button>
        </form>
    </div>
    <div class="col-md-6"></div>
</div>

SE1611_Group4_A3/SE1611_Group4_A3/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

SE1611_Group4_A3/SE1611_Group4_A3/Pages/Login.cshtml
@page "{handler?}"
@model SE1607_Group4_A3.Pages.LoginModel
@{
}
<h1>Login</h1>
<h2>User</h2>
@Html.ValidationMessage("LoginFailed", "", new{@class = "text-danger"})
<hr />
<div class="row">
    <div class="col-md-6">
       
        <div class="row">
            <form asp-action="POST">
                <label asp-for="User.UserName"></label><br />
                <span asp-validation-for="User.UserName" class="text-danger"></span><br />
                <input class="form-control" asp-for="User.UserName" /><br />

                <label asp-for="User.Password"></label><br />
                <span asp-validation-for="User.Password" class="text-danger"></span><br />
                <input class="form-control" asp-for="User.Password" /><br />

                <button class="btn btn-primary">Login</button><br />
            </form>
        </div>
    </div>
    <div class="col-md-6"></div>
</div>

SE1611_Group4_A3/SE1611_Group4_A3/Pages/Shopping.cshtml
@page
@model SE1607_Group4_A3.Pages.ShoppingModel
@{
}
<script>
   function pageHandler(isNext){
       var pageInput = document.getElementById('PageNum');
       if(isNext){
            pageInput.value = @(Model.PageNum*3+3 >= Model.Count ? Model.PageNum : Model.PageNum+1)
       } else {
           pageInput.value = @(Model.PageNum == 0 ? 0 : Model.PageNum-1)
       }
      document.getElementById("getForm").submit();
   }
</script>
<form method="get" id="getForm">
    <h1>Shopping</h1>
    <span>Genre name: </span>
    <select asp-for="GenreId" asp-items="Model.Genres"></select>
    <span> Find by name: </span>
    <input asp-for="Title"/>
    <button class="btn btn-primary">Search</button>
    <span>|</span>
    <input asp-for="PageNum" hidden/>
    <a asp-page="/Shopping">Back to full list</a>
</form>

<div class="row">
    @foreach(var album in Model.Albums)
    {
      @:<div class="col-md-3">
          <form asp-action="POST">
            <input asp-for="AlbumId" hidden="true" value="@album.AlbumId"/>
            <img src="@album.AlbumUrl" /><span style="color: var(--bs-primary)">$@album.Price</span>
            <p style="color: var(--bs-primary)">@album.Title</p>
            <p>Artist: @album.Artist.Name</p>
            <p>Genre: @album.Genre.Name</p>
            <button class="btn btn-primary" asp-page-handler="addCart">Add to cart</button>
          </form>
      @:</div>
    }
</div>
<div class="mt-3">
    <a  style="display:inline-block" onclick="pageHandler(false)"  class="btn btn-primary">Previous</a>
    <a  style="display:inline-block" onclick="pageHandler(true)" class="btn btn-primary">Next</a>
    <span>Page: @(Model.PageNum + 1) / @(Model.TotalPage + 1)</span>
</div>